version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_DB = ${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    env_file: ./backend/.env
  #backend:
  #  build:
  #    context: ./backend
  #  volumes:
  #    - ./backend:/app
  #  ports:
  #    - "8000:8000"
  #  env_file: ./backend/.env
  #  depends_on:
  #    - db

  #frontend:
  #  build:
  #    context: ./frontend
  #  volumes:
  #    - ./frontend:/app
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - backend
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
    

secrets:
  db_password:
    file: ./backend/db_password.txt

volumes:
  postgres_data: