"""updated user

Revision ID: 0ef5ef6a7175
Revises: cbaf79dd81b0
Create Date: 2024-05-26 21:05:41.214335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef5ef6a7175'
down_revision: Union[str, None] = 'cbaf79dd81b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_role', table_name='user')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
