"""updated

Revision ID: 23782cae6520
Revises: 0ef5ef6a7175
Create Date: 2024-05-27 00:32:19.737002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23782cae6520'
down_revision: Union[str, None] = '0ef5ef6a7175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cancha_id', sa.Integer(), nullable=True),
    sa.Column('reserva_time', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_estado'), 'reservations', ['estado'], unique=False)
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.drop_index('ix_reservation_estado', table_name='reservation')
    op.drop_index('ix_reservation_id', table_name='reservation')
    op.drop_table('reservation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cancha_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reserva_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.id'], name='reservation_cancha_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='reservation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservation_pkey')
    )
    op.create_index('ix_reservation_id', 'reservation', ['id'], unique=False)
    op.create_index('ix_reservation_estado', 'reservation', ['estado'], unique=False)
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_estado'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
