"""init

Revision ID: 409e38ac3cc6
Revises: 8151b007f910
Create Date: 2024-05-27 00:07:05.331892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409e38ac3cc6'
down_revision: Union[str, None] = '8151b007f910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancha', sa.Column('reserva_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cancha', 'reservation', ['reserva_id'], ['id'])
    op.drop_constraint('reservation_cancha_id_fkey', 'reservation', type_='foreignkey')
    op.drop_constraint('reservation_user_id_fkey', 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'cancha_id')
    op.drop_column('reservation', 'user_id')
    op.add_column('users', sa.Column('reserva_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'reservation', ['reserva_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'reserva_id')
    op.add_column('reservation', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('cancha_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reservation_user_id_fkey', 'reservation', 'users', ['user_id'], ['id'])
    op.create_foreign_key('reservation_cancha_id_fkey', 'reservation', 'cancha', ['cancha_id'], ['id'])
    op.drop_constraint(None, 'cancha', type_='foreignkey')
    op.drop_column('cancha', 'reserva_id')
    # ### end Alembic commands ###
