"""init

Revision ID: 641569e24b8a
Revises: 
Create Date: 2024-05-26 15:36:08.678074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641569e24b8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('fotografia', sa.String(), nullable=True),
    sa.Column('estado_disponibilidad', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancha_fotografia'), 'cancha', ['fotografia'], unique=False)
    op.create_index(op.f('ix_cancha_id'), 'cancha', ['id'], unique=False)
    op.create_index(op.f('ix_cancha_tipo'), 'cancha', ['tipo'], unique=False)
    op.create_index(op.f('ix_cancha_ubicacion'), 'cancha', ['ubicacion'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cancha_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_estado'), 'reservation', ['estado'], unique=False)
    op.create_index(op.f('ix_reservation_id'), 'reservation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_estado'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_cancha_ubicacion'), table_name='cancha')
    op.drop_index(op.f('ix_cancha_tipo'), table_name='cancha')
    op.drop_index(op.f('ix_cancha_id'), table_name='cancha')
    op.drop_index(op.f('ix_cancha_fotografia'), table_name='cancha')
    op.drop_table('cancha')
    # ### end Alembic commands ###
